### ISSUE TITLE
Add support for zero-amount payments

### ISSUE THREAD

**Issue by janspuro** [payout-one/payout_nodejs#27]
The current version of the package does not support the creation of zero-amount checkouts. The problem arises in the two methods for creating and verifying the signature due to the use of the `||` operator instead of `??`.

Lines related to this issue:
https://github.com/payout-one/payout_nodejs/blob/459853abddfabc813efb545033d867de38e5d658/src/index.ts#L352
https://github.com/payout-one/payout_nodejs/blob/459853abddfabc813efb545033d867de38e5d658/src/index.ts#L377

**Comment by martin-cernak** [comment]
Hello, thank you for report and also for solution, fixed version is published as 2.2.1
